<?php
require_once __DIR__ . '/../../includes/pdf.php';
$objects=db()->query("SELECT * FROM objects ORDER BY object_name")->fetchAll();
$objectId=(int)($_POST['object_id'] ?? $_GET['object_id'] ?? ($objects[0]['id'] ?? 0));
$object=null; $check=[]; $assigned=[];
if($objectId){ $stmt=db()->prepare('SELECT * FROM objects WHERE id=?'); $stmt->execute([$objectId]); $object=$stmt->fetch(); $stmt=db()->prepare('SELECT * FROM object_document_checks WHERE object_id=?'); $stmt->execute([$objectId]); $check=$stmt->fetch()?:[]; $stmt=db()->prepare("SELECT oqd.*, d.document_number,d.title,d.status doc_status, av.version_label assigned_version,av.document_date assigned_date, cv.id current_id, cv.version_label current_version, cv.document_date current_date, cv.change_type current_change FROM object_qm_documents oqd JOIN qm_documents d ON d.id=oqd.document_id JOIN qm_document_versions av ON av.id=oqd.document_version_id LEFT JOIN qm_document_versions cv ON cv.document_id=d.id AND cv.is_current=1 WHERE oqd.object_id=? ORDER BY d.document_number"); $stmt->execute([$objectId]); $assigned=$stmt->fetchAll(); }
$versions=db()->query("SELECT v.id,d.document_number,d.title,v.document_date,v.version_label FROM qm_document_versions v JOIN qm_documents d ON d.id=v.document_id ORDER BY d.document_number,v.document_date DESC")->fetchAll();
function docAssignmentStatus(array $r): string { if($r['doc_status']==='aus_qm_entfernt'||$r['current_change']==='aus_qm_entfernt') return 'aus QM entfernt'; return (int)$r['document_version_id']===(int)$r['current_id']?'aktuell':'veraltet'; }
?>
<div class="panel"><h2>Dokumentenkontrolle</h2><form method="post" class="toolbar"><label>Objekt <select id="objectSelect"><?php foreach($objects as $o): ?><option value="<?= (int)$o['id'] ?>" <?= $objectId===(int)$o['id']?'selected':'' ?>><?= e($o['object_name']) ?></option><?php endforeach; ?></select></label><button type="button" onclick="$.post('ajax/load_module.php',{csrf_token:csrfToken(),module_key:'document_control',object_id:$('#objectSelect').val()},r=>$('#main-content').html(r.html))">anzeigen</button></form></div>
<?php if($object): ?><div class="panel"><h3>Stammdaten: <?= e($object['object_name']) ?></h3><p><?= e($object['address']) ?> · <?= statusBadge($object['status']) ?></p><form class="ajax-form form-grid" action="ajax/document_control.php" data-reload="document_control" method="post"><?= csrfField() ?><input type="hidden" name="action" value="save_check"><input type="hidden" name="object_id" value="<?= $objectId ?>"><label>Datum Arbeitsanweisung<input type="date" name="work_instruction_date" value="<?= e($check['work_instruction_date']??'') ?>"></label><label>Arbeitsanweisung geprüft am<input type="date" name="work_instruction_checked_at" value="<?= e($check['work_instruction_checked_at']??'') ?>"></label><label>Datum GBU<input type="date" name="gbu_date" value="<?= e($check['gbu_date']??'') ?>"></label><label>GBU geprüft am<input type="date" name="gbu_checked_at" value="<?= e($check['gbu_checked_at']??'') ?>"></label><label>Bemerkung<textarea name="notes"><?= e($check['notes']??'') ?></textarea></label><div><button>Kontrolle speichern</button></div></form></div>
<div class="panel"><h3>QM-Dokument zuordnen</h3><form class="ajax-form form-grid" action="ajax/document_control.php" data-reload="document_control" method="post"><?= csrfField() ?><input type="hidden" name="action" value="assign_doc"><input type="hidden" name="object_id" value="<?= $objectId ?>"><label>Version im Ordner<select name="document_version_id"><?php foreach($versions as $v): ?><option value="<?= (int)$v['id'] ?>"><?= e($v['document_number'].' - '.$v['title'].' / '.$v['document_date'].' '.$v['version_label']) ?></option><?php endforeach; ?></select></label><label>Zugeordnet am<input type="date" name="assigned_at"></label><label>Letzte Prüfung<input type="date" name="last_checked_at"></label><label>Bemerkung<textarea name="notes"></textarea></label><div><button>Zuordnung speichern</button></div></form></div>
<div class="panel"><h3>Zugeordnete Dokumente</h3><?php if(pdfAvailable()): ?><form action="ajax/pdf_export.php" method="post" target="_blank"><?= csrfField() ?><input type="hidden" name="object_id" value="<?= $objectId ?>"><button>PDF-Übersicht exportieren</button></form><?php else: ?><div class="notice">PDF-Export ist vorbereitet, aber FPDF ist noch nicht unter /vendor/fpdf/fpdf.php installiert.</div><?php endif; ?><table class="data-table"><thead><tr><th>Dokumentnummer</th><th>Name</th><th>Version im Objektordner</th><th>Aktuelle QM-Version</th><th>Status</th><th>Letzte Prüfung</th></tr></thead><tbody><?php foreach($assigned as $a): $s=docAssignmentStatus($a); ?><tr><td><?= e($a['document_number']) ?></td><td><?= e($a['title']) ?></td><td><?= e(($a['assigned_date']?:'').' '.$a['assigned_version']) ?></td><td><?= e(($a['current_date']?:'').' '.$a['current_version']) ?></td><td><?= statusBadge($s) ?></td><td><?= e($a['last_checked_at']) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
